version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "deps"
      include: "scope"
    reviewers:
      - "@alexia-ai/core"
    assignees:
      - "@alexia-ai/core"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
    versioning-strategy: "increase"
    commit-message:
      prefix: "workflow"
      include: "scope"
    reviewers:
      - "@alexia-ai/core"
    assignees:
      - "@alexia-ai/core"

  - package-ecosystem: "github"
    directories:
      - "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    target-branch: "main"
